version: "2"
formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gochecknoglobals
    - gochecknoinits
    - gocritic