version: "2"
formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - ginkgolinter
    - revive
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: exported
          disabled: true