version: "2"
formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - ginkgolinter
    - revive
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - errorlint
    - errname
    - err113
    - errchkjson
    - errname
    - errorlint
    - fatcontext
    - godox
    - gosec
    - iface
    - intrange
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
  settings:
    gosec:
      excludes:
        - G404
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: exported
          disabled: true