test:
	go test ./src/hotline/... -coverprofile=./cover.out -covermode=atomic -coverpkg=./src/hotline/...
	go test ./src/app/... -coverprofile=./cover.app.out -covermode=atomic -coverpkg=./src/hotline/...

deps:
	go mod download

lint:
	govulncheck
	golangci-lint run ./src/hotline/...
	gocritic check ./src/hotline/...
	golangci-lint run ./src/app/...
	gocritic check ./src/app/...

run-infra:
	docker-compose -f ./examples/infra/docker-compose.yml up