services:
  otel:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel.yaml"]
    volumes:
      - ./otel.yaml:/etc/otel.yaml
    ports:
      - "4318:4318"
      - "9091:9090"
      - "55679:55679"
  envoy:
    image: envoyproxy/envoy:v1.33.2
    ports:
     - 10000:10000
    command: envoy -c /etc/envoy/envoy.yaml --log-level info
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
#  prometheus:
#    image: prom/prometheus:latest
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"