receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
processors:
  transform:
    error_mode: ignore
    trace_statements:
      - replace_all_patterns(span.attributes, "key", "http[.]method", "http.request.method")
      - replace_all_patterns(span.attributes, "key", "http[.]status_code", "http.response.status_code")
      - replace_all_patterns(span.attributes, "key", "http[.]url", "url.full")
      - replace_all_patterns(span.attributes, "key", "http[.]protocol", "network.protocol.version")
extensions:
  health_check: {}
exporters:
  prometheus:
    endpoint: "0.0.0.0:9090"
    metric_expiration: 1m
  debug:
    verbosity: detailed
service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    traces:
      receivers: [ otlp ]
      exporters: [debug]
      processors: [transform]