name: go-tests
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  golangci:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: 1.25.1
          cache-dependency-path: |
            hotline/go.sum
            app/go.sum
            go.work.sum
      - name: run tests
        run: |
          make test
          make cover