name: go-tests
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  test-ci:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: 1.25.1
          check-latest: false
          cache-dependency-path: |
            hotline/go.sum
            app/go.sum
            go.work.sum
      - name: run tests
        run: |
          make clean-cache
          make test
          make cover
          make clean-cache
      - name: check hotline test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          source-dir: ./src/hotline
          threshold-total: 100
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
          git-branch: badges
          git-file-name: .badges/main/hotline.svg
      - name: check app test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.app.out
          source-dir: ./src/app
          threshold-total: 10
          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
          git-branch: badges
          git-file-name: .badges/main/app.svg
