name: go-tests
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  golangci:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: run tests
        run: |
          cd src
          make test
      - name: check test coverage
        uses: vladopajic/go-test-coverage@992aa9921a42c39d1fe0015d32593f0820589586 # v2
        with:
          config: ./.github/.testcoverage.yml
      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          coverage-file: src/cover.out
          report: true
          chart: true
          amend: true